### ISSUE TITLE
Input accept-key not working

### ISSUE THREAD

**Issue by rafael-moraes-isaac** [goodwithtech/dockle-action#1]
Sample to reproduce the bug

```yaml
      - name: Dockle Lint
        id: dockle
        uses: goodwithtech/dockle-action@main
        with:
          image: '${{ inputs.image }}'
          format: 'list'
          exit-code: 1
          exit-level: 'warn'
          accept-key: 'KEY_1,KEY_2'
```

It looks like the env vars are not being passed to the container
