### ISSUE TITLE
Timeout error after upgrade

### ISSUE THREAD

**Issue by loganmarchione** [goodwithtech/dockle-action#5]
I recently upgraded the GitHub Action from `goodwithtech/dockle-action@0.1.0` to `goodwithtech/dockle-action@v0.1.1`, but am now getting this error in all of my GitHub Actions runs.

```
 2023/09/10 05:06:00 could not parse  as duration for flag timeout, t: time: invalid duration ""
```

Here is how I'm calling the Action.

```
    - name: Container scan with Dockle
      uses: goodwithtech/dockle-action@v0.1.1
      with:
        image: '${{ env.USER }}/${{ env.REPO }}:${{ env.VERSION }}'
        format: 'list'
        exit-code: '1'
        exit-level: 'warn'
        ignore: 'CIS-DI-0001'
```
